import './globals.css';
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import ScrollToTopButton from "../components/ScrollToTopButton";
import Footer from "../components/Footer";
export const metadata = {
  title: "DIMA Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Header />
        <Navbar />
        <ScrollToTopButton/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
